substitutions:
  _REGION: europe-west2
  _REPO: web-repo
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/frontend-web:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/backend-api:$SHORT_SHA', './personal_assistant']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/frontend-web:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/backend-api:$SHORT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'frontend-web', '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/frontend-web:$SHORT_SHA', '--platform=managed', '--region=$_REGION', '--allow-unauthenticated']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'backend-api', '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/backend-api:$SHORT_SHA', '--platform=managed', '--region=$_REGION', '--allow-unauthenticated', '--update-secrets=GROQ_API_KEY=projects/$PROJECT_ID/secrets/GROQ_API_KEY:latest']
images:
- $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/frontend-web:$SHORT_SHA
- $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/backend-api:$SHORT_SHA 